spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      compression-type: lz4
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries:  0
      batch-size: 16384
      buffer-memory: 33554432
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ideal-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 20000ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


